# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

# ebuild generated by hackport 0.5.6

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Automates most of your plain text accounting data entry in ledger format"
HOMEPAGE="http://johannesgerer.com/buchhaltung"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/aeson-1.0.0:=[profile?]
	dev-haskell/ansi-wl-pprint:=[profile?]
	dev-haskell/async:=[profile?]
	dev-haskell/boxes:=[profile?]
	>=dev-haskell/cassava-0.4.1.0:=[profile?]
	dev-haskell/data-default:=[profile?]
	>=dev-haskell/decimal-0.4.2:=[profile?]
	dev-haskell/edit-distance:=[profile?]
	dev-haskell/file-embed:=[profile?]
	dev-haskell/formatting:=[profile?]
	dev-haskell/hashable:=[profile?]
	dev-haskell/haskeline:=[profile?]
	dev-haskell/hint:=[profile?]
	>=dev-haskell/hledger-1.1:=[profile?]
	<dev-haskell/hledger-1.9:=[profile?]
	>=dev-haskell/hledger-lib-1.1:=[profile?]
	<dev-haskell/hledger-lib-1.9:=[profile?]
	dev-haskell/lens:=[profile?]
	dev-haskell/lifted-base:=[profile?]
	dev-haskell/listlike:=[profile?]
	>=dev-haskell/megaparsec-5.0.0:=[profile?]
	dev-haskell/missingh:=[profile?]
	dev-haskell/monad-control:=[profile?]
	dev-haskell/mtl:=[profile?]
	>=dev-haskell/optparse-applicative-0.13:=[profile?]
	dev-haskell/parsec:=[profile?]
	dev-haskell/regex-compat:=[profile?]
	dev-haskell/regex-tdfa:=[profile?]
	dev-haskell/regex-tdfa-text:=[profile?]
	dev-haskell/safe:=[profile?]
	dev-haskell/semigroups:=[profile?]
	dev-haskell/split:=[profile?]
	dev-haskell/strict:=[profile?]
	dev-haskell/temporary:=[profile?]
	dev-haskell/text:=[profile?]
	dev-haskell/unordered-containers:=[profile?]
	dev-haskell/vector:=[profile?]
	dev-haskell/yaml:=[profile?]
	>=dev-lang/ghc-7.8.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.18.1.3
"

PATCHES=(
       "${FILESDIR}"/${P}-semigroups-fix.patch
)
